language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    
notifications:
  email:
    - pohl@physik.uni-bonn.de

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt --cache-dir $HOME/.pip-cache
  - python setup.py develop

# Run test
script: nosetests
