build: false  # Tell appveyor to not use msbuild

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
      PYTHON_ARCH: "64"
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37
      PYTHON_ARCH: "32"
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37-x64
      PYTHON_ARCH: "64"

install:
  # Miniconda Python setup + external packages installation
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%PATH%
  - conda update --yes conda
  - conda info -a
  - conda install --yes numpy numba nose
  - pip install -e .
  - conda list

test_script:
  - nosetests
