environment:
  matrix:
    - PYTHON: 2.7
    - PYTHON: 3.5

platform:
  - x86
  - x64

install:
  # Miniconda setup + necessary external packages
  - set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%  # Miniconda is already installed on appveyor: https://github.com/appveyor/ci/issues/359
  - conda install --yes numpy numba=0.22.1 future nose docutils
  - conda info -a
  - conda list
  - python setup.py develop

test_script:
  - nosetests